#ifndef SMALL_VALUES_H
#define SMALL_VALUES_H

#include <string>
#include <sstream>
#include <vector>

#include "small_env.hpp"
#include "small_lang_forwards.hpp"
#include "ast/small_expr.hpp"
#include "ast/small_ops.hpp"

// Abstract base class for values generated by evaluating a program.
// Each derived class must implement the arithmetic and comparative ops. Since
// there's only one Boolean type, the evaluator handles boolean expressions.
class Value {
    public:
        virtual ~Value() {}
        virtual Value *clone() const = 0;
        virtual std::string toString() const = 0;

        virtual Value *add(const Value *rhs) const = 0;
        virtual Value *sub(const Value *rhs) const = 0;
        virtual Value *mul(const Value *rhs) const = 0;
        virtual Value *div(const Value *rhs) const = 0;
        virtual Value *mod(const Value *rhs) const = 0;

        virtual bool eq(const Value *rhs) const = 0;
        virtual bool lt(const Value *rhs) const = 0;

        virtual bool lte(const Value *rhs) const {
            return !(rhs->lt(this));
        }

        virtual bool gt(const Value *rhs) const {
            return rhs->lt(this);
        }

        virtual bool gte(const Value *rhs) const {
            return !(this->lt(rhs));
        }
};

class VInt : public Value {
    int value;
    Value *arith_op(Op2 op, const Value *rhs) const;
    bool comp_op(Op2 op, const Value *rhs) const;

    public:
    VInt (int v);
    VInt (const VInt &other);
    virtual ~VInt();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    int getValue() const;
};

class VFloat : public Value {
    float value;
    Value *arith_op(Op2 op, const Value *rhs) const;
    bool comp_op(Op2 op, const Value *rhs) const;

    public:
    VFloat (float v);
    VFloat (const VFloat &other);
    virtual ~VFloat();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    float getValue() const;
};

class VBool : public Value {
    bool value;
    public:
    VBool (bool b);
    VBool (const VBool &other);
    virtual ~VBool();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    bool getValue() const;
};

class VChar : public Value {
    char value;
    public:
    VChar (char c);
    VChar (const VChar &other);
    virtual ~VChar();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    char getValue() const;
};

class VString : public Value {
    std::string value;
    public:
    VString (std::string v);
    VString (const char* str);
    VString (const VString &other);
    virtual ~VString();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    std::string getValue() const;
};

class VList : public Value {
    std::vector<Value*> value;
    public:
    VList ();
    VList (std::vector<Value*> l);
    VList (Value *e);
    VList (const VList &other);
    virtual ~VList();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    std::vector<Value*> getValue() const;
};

class VTuple : public Value {
    std::vector<Value*> value;
    int size;
    public:
    VTuple();
    VTuple (std::vector<Value*> l);
    VTuple (const VTuple &other);
    virtual ~VTuple();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    std::vector<Value*> getValue() const;
    int getSize() const;
};

class VClos : public Value {
    ELambda *lambda;
    Env env;
    public:
    VClos (ELambda *l, Env e);
    VClos (const VClos &other);
    virtual ~VClos();
    virtual Value *clone() const;
    virtual std::string toString() const;

    virtual Value *add(const Value *rhs) const;
    virtual Value *sub(const Value *rhs) const;
    virtual Value *mul(const Value *rhs) const;
    virtual Value *div(const Value *rhs) const;
    virtual Value *mod(const Value *rhs) const;

    virtual bool eq(const Value *rhs) const;
    virtual bool lt(const Value *rhs) const;

    ELambda *getLambda() const;
    Env getEnv() const;
};

#endif
